version: '3.4'

services:
    app:
        image: ${DOCKER_REGISTRY-}app
        build:
            context: .
            dockerfile: app/Dockerfile
        depends_on:
            - redis
            - mongo
        networks:
            - default
            
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - default
            
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        networks:
            - default

networks:
  default:
    driver: bridge
    name: db_network